name: PyPI Deployment

on: [push]
 # release:
  #  types: [created]
 
jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist
        twine upload --skip-existing dist/*

  build_wheels:
    name: Build wheels on ${{ matrix.archs }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        archs: [auto, aarch64]
        exclude:
          - os: windows-latest
            archs: aarch64
          - os: macos-latest
            archs: aarch64
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        if: matrix.archs == 'aarch64'
        id: qemu
        uses: docker/setup-qemu-action@v1

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BUILD: 'cp37-* cp38-* cp39-*'
          CIBW_BEFORE_BUILD: pip install cython numpy
          CIBW_SKIP: '*-manylinux*_i686'
          CIBW_ARCHS: ${{ matrix.archs }}
          #CIBW_TEST_REQUIRES: tox
          #CIBW_TEST_COMMAND: pwd
          #CIBW_BUILD_VERBOSITY: 1        

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
